export type TripoliSource = {
  id: string;
  title: string;
  url: string;
  section?: string;
  content: string;
  tags: string[];
};

export const getTripoliKnowledge = (): TripoliSource[] => [
  {
    id: "tripoli-media",
    title: "Tripoli Media",
    url: "/",
    section: "Sitio",
    content:
      "ES: Tripoli Media es un ecosistema digital con contenido editorial especializado, anal\u00edtica avanzada y soluciones web para impulsar visibilidad y decisiones medibles. EN: Tripoli Media is a digital ecosystem with specialized editorial content, advanced analytics, and web solutions to drive visibility and measurable decisions.",
    tags: ["tripoli", "media", "sitio", "site", "descripcion", "about", "ecosistema"],
  },
  {
    id: "contacto",
    title: "Contacto",
    url: "/contacto",
    section: "Contacto",
    content:
      "ES: Contacto de Tripoli Media. Tel\u00e9fono y WhatsApp: +52 33 2817 5756. Correo: contacto@tripoli.media. Direcci\u00f3n: P. de los Virreyes 45, Puerta de Hierro, 45116 Zapopan, Jal. EN: Tripoli Media contact. Phone and WhatsApp: +52 33 2817 5756. Email: contacto@tripoli.media. Address: P. de los Virreyes 45, Puerta de Hierro, 45116 Zapopan, Jal.",
    tags: [
      "contacto",
      "contact",
      "telefono",
      "tel",
      "numero",
      "phone",
      "whatsapp",
      "correo",
      "email",
      "mail",
      "direccion",
      "address",
      "ubicacion",
      "zapopan",
      "virreyes",
      "puerta",
      "hierro",
    ],
  },
  {
    id: "servicios",
    title: "Servicios",
    url: "/servicios",
    section: "Servicios",
    content:
      "ES: Tripoli Media ofrece soluciones editoriales, anal\u00edticas y web enfocadas en visibilidad, desempe\u00f1o digital y posicionamiento estrat\u00e9gico. EN: Tripoli Media offers editorial, analytics, and web solutions focused on visibility, digital performance, and strategic positioning.",
    tags: ["servicios", "services", "editorial", "analitica", "analytics", "web", "soluciones", "solutions"],
  },
  {
    id: "servicios-editorial",
    title: "Tripoli Publishing House",
    url: "/servicios",
    section: "Servicios",
    content:
      "ES: Tripoli Publishing House brinda cobertura editorial para posicionamiento de marca y visibilidad sectorial; incluye notas editoriales, art\u00edculos de opini\u00f3n y publirreportajes, con distribuci\u00f3n en LinkedIn, Facebook y X. EN: Tripoli Publishing House provides editorial coverage for brand positioning and sector visibility, including editorial notes, opinion pieces, advertorials, and distribution on LinkedIn, Facebook, and X.",
    tags: ["publishing", "editorial", "contenido", "content", "linkedin", "facebook", "x", "twitter"],
  },
  {
    id: "servicios-analytics",
    title: "Tripoli Analytic Services",
    url: "/servicios",
    section: "Servicios",
    content:
      "ES: Tripoli Analytic Services ofrece anal\u00edtica avanzada para decisiones ejecutivas, optimizaci\u00f3n de ROI y crecimiento basado en datos; incluye Google Analytics, Meta Analytics, definici\u00f3n de KPIs y pauta digital. EN: Tripoli Analytic Services delivers advanced analytics for executive decisions, ROI optimization, and data-driven growth, including Google Analytics, Meta Analytics, KPI definition, and paid media.",
    tags: ["analytics", "analitica", "kpi", "roi", "google", "meta", "ads", "pauta", "reporting"],
  },
  {
    id: "servicios-web",
    title: "Tripoli Web Services",
    url: "/servicios",
    section: "Servicios",
    content:
      "ES: Tripoli Web Services crea plataformas web personalizadas enfocadas en rendimiento, seguridad y SEO, con integraciones de comercio digital. EN: Tripoli Web Services builds custom web platforms focused on performance, security, and SEO with digital commerce integrations.",
    tags: ["web", "seo", "seguridad", "security", "ecommerce", "retail", "platform", "plataformas"],
  },
  {
    id: "conocenos",
    title: "Con\u00f3cenos",
    url: "/conocenos",
    section: "Con\u00f3cenos",
    content:
      "ES: Tripoli Media es un ecosistema digital que integra contenido editorial especializado, anal\u00edtica avanzada y soluciones web para ganar visibilidad, organizar informaci\u00f3n y tomar decisiones medibles. EN: Tripoli Media is a digital ecosystem combining specialized editorial content, advanced analytics, and web solutions to gain visibility, organize information, and make measurable decisions.",
    tags: ["conocenos", "about", "ecosistema", "ecosystem", "editorial", "analytics", "web", "tripoli"],
  },
  {
    id: "noticias",
    title: "Noticias y notas",
    url: "/",
    section: "Inicio",
    content:
      "ES: En la p\u00e1gina principal hay secciones de \u00daltimas noticias por categor\u00eda. EN: The homepage includes latest news sections by category.",
    tags: ["noticias", "news", "notas", "notes", "ultimas", "latest", "inicio", "home"],
  },
  {
    id: "categoria-consumo",
    title: "Consumo y Retail",
    url: "/categoria/consumo-y-retail",
    section: "Categor\u00edas",
    content:
      "ES: Consumo y Retail incluye Fabricantes y Proveedores, Cadenas Comerciales y Tiendas de Conveniencia. EN: Consumer & Retail includes Manufacturers & Suppliers, Retail Chains, and Convenience Stores.",
    tags: ["consumo", "retail", "fabricantes", "proveedores", "cadenas", "comerciales", "conveniencia", "tiendas"],
  },
  {
    id: "categoria-entretenimiento",
    title: "Entretenimiento y Cultura",
    url: "/categoria/entretenimiento-y-cultura",
    section: "Categor\u00edas",
    content:
      "ES: Entretenimiento y Cultura incluye Productoras de Contenido, Recintos Culturales y Festivales, Eventos y Artistas. EN: Entertainment & Culture includes Content Producers, Cultural Venues, and Festivals, Events & Artists.",
    tags: ["entretenimiento", "cultura", "productoras", "contenido", "recintos", "culturales", "festivales", "eventos", "artistas"],
  },
  {
    id: "categoria-industria-ti",
    title: "Industria TI",
    url: "/categoria/industria-ti",
    section: "Categor\u00edas",
    content:
      "ES: Industria TI incluye Fabricantes de Tecnolog\u00eda, Mayoristas TI y Canales de Distribuci\u00f3n. EN: IT Industry includes Technology Manufacturers, IT Wholesalers, and Distribution Channels.",
    tags: ["industria", "ti", "tecnologia", "mayoristas", "canales", "distribucion"],
  },
  {
    id: "categoria-infraestructura",
    title: "Infraestructura Social",
    url: "/categoria/infraestructura-social",
    section: "Categor\u00edas",
    content:
      "ES: Infraestructura Social incluye Proveedores de Materiales, Desarrolladores de Proyectos y Promotores Inmobiliarios. EN: Social Infrastructure includes Materials Suppliers, Project Developers, and Real Estate Developers.",
    tags: ["infraestructura", "social", "proveedores", "materiales", "desarrolladores", "promotores", "inmobiliarios"],
  },
  {
    id: "categoria-politica",
    title: "Pol\u00edtica y Leyes",
    url: "/categoria/politica-y-leyes",
    section: "Categor\u00edas",
    content:
      "ES: Pol\u00edtica y Leyes incluye Organismos P\u00fablicos, Administraci\u00f3n Estatal y Local, y Servicios Jur\u00eddicos. EN: Politics & Law includes Public Agencies, State & Local Administration, and Legal Services.",
    tags: ["politica", "leyes", "organismos", "publicos", "administracion", "estatal", "local", "juridicos"],
  },
  {
    id: "categoria-salud",
    title: "Sector Salud",
    url: "/categoria/sector-salud",
    section: "Categor\u00edas",
    content:
      "ES: Sector Salud incluye Fabricantes de Equipos e Insumos, Instituciones de Salud y Especialistas M\u00e9dicos. EN: Health Sector includes Equipment & Supplies Manufacturers, Healthcare Institutions, and Medical Specialists.",
    tags: ["salud", "sector", "equipos", "insumos", "instituciones", "especialistas", "medicos"],
  },
  {
    id: "horarios-atencion",
    title: "Horarios de Atención",
    url: "/contacto",
    section: "Contacto",
    content:
      "ES: Nuestro horario de atención es de lunes a viernes de 09:00 a 18:00 hrs, y sábados de 09:00 a 13:00 hrs (GMT-6). Los domingos permanecemos cerrados. EN: Our business hours are Monday through Friday from 9:00 AM to 6:00 PM, and Saturdays from 9:00 AM to 1:00 PM (GMT-6). We are closed on Sundays.",
    tags: [
      "horarios",
      "hours",
      "atencion",
      "service",
      "tiempo",
      "time",
      "cuando",
      "when",
      "abierto",
      "open",
      "cerrado",
      "closed",
      "sabado",
      "saturday",
      "domingo",
      "sunday",
      "lunes",
      "monday",
      "viernes",
      "friday",
      "semana",
      "week",
      "horario",
      "schedule",
      "contacto",
    ],
  },
  {
    id: "agendar-cita",
    title: "Agendar Cita",
    url: "https://cal.com/tripolimedia/reunion-de-1-hr",
    section: "Contacto",
    content:
      "ES: Para agendar una reunión estratégica de 1 hora directamente con el equipo, utiliza nuestro calendario oficial aquí: https://cal.com/tripolimedia/reunion-de-1-hr. EN: To schedule a 1-hour strategic meeting directly with our team, use our official calendar here: https://cal.com/tripolimedia/reunion-de-1-hr.",
    tags: [
      "cita",
      "appointment",
      "agendar",
      "book",
      "booking",
      "reunion",
      "meeting",
      "link",
      "enlace",
      "cal",
      "calendario",
      "calendar",
      "programar",
      "schedule",
      "demo",
      "consulta",
      "consultation",
      "reservar",
      "reserve",
      "hablar",
      "talk",
      "contacto",
      "junta",
    ],
  },
  {
    id: "sectores-principales",
    title: "Sectores de Especialización",
    url: "/servicios",
    section: "Servicios",
    content:
      "ES: Tripoli Media estructura sus servicios en 6 grandes sectores: 1) Consumo y Retail, 2) Entretenimiento y Cultura, 3) Industria TI, 4) Infraestructura Social, 5) Política y Leyes, y 6) Sector Salud. EN: Tripoli Media structures its services into 6 main sectors: 1) Consumer & Retail, 2) Entertainment & Culture, 3) IT Industry, 4) Social Infrastructure, 5) Politics & Law, and 6) Healthcare.",
    tags: [
      "sectores",
      "sectors",
      "industrias",
      "industries",
      "mercado",
      "market",
      "categorias",
      "categories",
      "areas",
      "especialidad",
      "specialty",
      "verticales",
      "verticals",
      "nichos",
      "niches",
      "segmentos",
      "segments",
      "servicios",
    ],
  },
  {
    id: "detalle-subcategorias",
    title: "Subcategorías y Nichos",
    url: "/servicios",
    section: "Servicios",
    content:
      "ES: Atendemos las siguientes subcategorías específicas: 1. Consumo y Retail (Fabricantes y Proveedores, Cadenas Comerciales, Tiendas de Conveniencia). 2. Entretenimiento y Cultura (Productoras de Contenido, Recintos Culturales, Festivales, Eventos y Artistas). 3. Industria TI (Fabricantes de Tecnología, Mayoristas TI, Canales de Distribución). 4. Infraestructura Social (Proveedores de Materiales, Desarrolladores de Proyectos, Promotores Inmobiliarios). 5. Política y Leyes (Organismos Públicos, Administración Estatal y Local, Servicios Jurídicos). 6. Sector Salud (Fabricantes de equipos e insumos, Instituciones de Salud, Especialistas Médicos). EN: Our specific subcategories include: Manufacturers & Suppliers, Commercial Chains, Convenience Stores, Content Producers, Cultural Venues, Festivals/Artists, Tech Manufacturers, IT Wholesalers, Distribution Channels, Material Suppliers, Project Developers, Real Estate Promoters, Public Bodies, State/Local Admin, Legal Services, Equipment Manufacturers, Health Institutions, and Medical Specialists.",
    tags: [
      "fabricantes",
      "manufacturers",
      "proveedores",
      "suppliers",
      "cadenas",
      "chains",
      "tiendas",
      "stores",
      "conveniencia",
      "convenience",
      "productoras",
      "producers",
      "recintos",
      "venues",
      "festivales",
      "festivals",
      "eventos",
      "events",
      "artistas",
      "artists",
      "tecnologia",
      "technology",
      "mayoristas",
      "wholesalers",
      "distribucion",
      "distribution",
      "canales",
      "channels",
      "materiales",
      "materials",
      "desarrolladores",
      "developers",
      "inmobiliarios",
      "real estate",
      "promotores",
      "promoters",
      "organismos",
      "agencies",
      "publicos",
      "public",
      "administracion",
      "administration",
      "juridicos",
      "legal",
      "insumos",
      "supplies",
      "instituciones",
      "institutions",
      "especialistas",
      "specialists",
      "medicos",
      "medical",
      "subcategorias",
      "subcategories",
      "nichos",
      "niches",
    ],
  },
];
